from django.db import models
from django.contrib.auth.models import User

class Users(models.Model):
    pas = models.CharField(max_length=20, null=True, blank=True)
    FIO = models.CharField(max_length=50)
    userStatus = models.CharField(max_length=20)
    age = models.IntegerField(null = True, blank=True)
    gender = models.CharField(max_length=20, null=True, blank=True)
    adress = models.CharField(max_length=50, null=True, blank=True)
    predmet = models.CharField(max_length=20, null=True, blank=True)
    experience = models.IntegerField(null = True, blank=True)
    clas = models.CharField(max_length=20, null=True, blank=True)
    mat = models.CharField(max_length=50, null=True, blank=True)
    rus = models.CharField(max_length=50, null=True, blank=True)
    bio = models.CharField(max_length=50, null=True, blank=True)
    him = models.CharField(max_length=50, null=True, blank=True)
    fizra = models.CharField(max_length=50, null=True, blank=True)
    obj = models.CharField(max_length=50, null=True, blank=True)
    fizika = models.CharField(max_length=50, null=True, blank=True)
    user_info = models.ForeignKey(User, on_delete=models.CASCADE)

class Jurnal(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(null=True, blank=True)
    predmet = models.CharField(max_length=20, null=True, blank=True)
    num = models.IntegerField(null=True, blank=True)

class timetable(models.Model):
    clas = models.CharField(max_length=20)
    date = models.DateField(null=True, blank=True)
    predmet1 = models.CharField(max_length=20, null=True, blank=True)
    predmet2 = models.CharField(max_length=20, null=True, blank=True)
    predmet3 = models.CharField(max_length=20, null=True, blank=True)
    predmet4 = models.CharField(max_length=20, null=True, blank=True)
    predmet5 = models.CharField(max_length=20, null=True, blank=True)
    predmet6 = models.CharField(max_length=20, null=True, blank=True)
    predmet7 = models.CharField(max_length=20, null=True, blank=True)
    dz1 = models.CharField(max_length=50, null=True, blank=True)
    dz2 = models.CharField(max_length=50, null=True, blank=True)
    dz3 = models.CharField(max_length=50, null=True, blank=True)
    dz4 = models.CharField(max_length=50, null=True, blank=True)
    dz5 = models.CharField(max_length=50, null=True, blank=True)
    dz6 = models.CharField(max_length=50, null=True, blank=True)
    dz7 = models.CharField(max_length=50, null=True, blank=True)
    topic1 = models.CharField(max_length=50, null=True, blank=True)
    topic2 = models.CharField(max_length=50, null=True, blank=True)
    topic3 = models.CharField(max_length=50, null=True, blank=True)
    topic4 = models.CharField(max_length=50, null=True, blank=True)
    topic5 = models.CharField(max_length=50, null=True, blank=True)
    topic6 = models.CharField(max_length=50, null=True, blank=True)
    topic7 = models.CharField(max_length=50, null=True, blank=True)