# Generated by Django 4.1.7 on 2023-03-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('FIO', models.CharField(max_length=50)),
                ('userStatus', models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('PUPIL', 'pupil')], max_length=20)),
            ],
        ),
    ]
