# Generated by Django 4.1.7 on 2023-03-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uspevaimost', '0005_alter_users_userstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='pas',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
