# Generated by Django 4.1.7 on 2023-03-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uspevaimost', '0011_alter_users_age_alter_users_bio_alter_users_clas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clas', models.CharField(max_length=20)),
                ('day', models.CharField(max_length=20)),
                ('predmet', models.CharField(max_length=20)),
                ('dz', models.CharField(max_length=50)),
            ],
        ),
    ]
