# Generated by Django 4.1.7 on 2023-03-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uspevaimost', '0014_timetable_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='dz',
            new_name='dz1',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='day',
        ),
        migrations.AddField(
            model_name='timetable',
            name='dz2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='dz3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='dz4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='dz5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='dz6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='dz7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
