# Generated by Django 4.1.7 on 2023-06-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uspevaimost', '0016_jurnal'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
