# Generated by Django 4.1.7 on 2023-06-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uspevaimost', '0017_users_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='adress',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
