# Generated by Django 4.1.7 on 2023-06-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uspevaimost', '0018_users_adress_users_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='topic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
