# Generated by Django 4.1.7 on 2023-06-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uspevaimost', '0019_timetable_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='topic',
            new_name='topic1',
        ),
        migrations.AddField(
            model_name='timetable',
            name='topic2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='topic3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='topic4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='topic5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='topic6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='topic7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
